"""Execution-focused reviewer workspace for the public Vice CEO demo."""

from __future__ import annotations


def render_demo_console() -> str:
    """Render the work queue without granting the public viewer delivery authority."""

    return """<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Vice CEO — Work</title>
  <style>
    :root { color-scheme:light; --ink:#172925; --muted:#63716d; --line:#dfe6e2; --wash:#f6f8f7; --forest:#124f3b; --forest-deep:#0b3b2d; --danger:#a3433b; --danger-wash:#fff8f7; --focus:#b7dccd; }
    * { box-sizing:border-box; } html { scroll-behavior:smooth; } body { margin:0; background:#fff; color:var(--ink); font:15px/1.5 Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif; }
    a { color:inherit; } button { font:inherit; } .topbar { display:flex; align-items:center; gap:34px; min-height:72px; padding:0 48px; border-bottom:1px solid var(--line); } .brand { flex:0 0 auto; color:var(--forest); font:400 2.15rem/.9 Georgia,"Times New Roman",serif; letter-spacing:-.075em; text-decoration:none; } .primary-nav { display:flex; align-items:stretch; gap:33px; height:72px; margin:auto; } .primary-nav a { display:grid; place-items:center; border-bottom:2px solid transparent; color:var(--muted); font-size:.91rem; font-weight:650; text-decoration:none; } .primary-nav a.active,.primary-nav a:hover { border-color:var(--forest); color:var(--ink); } .owner { display:flex; align-items:center; gap:10px; color:var(--muted); font-size:.88rem; } .avatar { display:grid; place-items:center; width:31px; height:31px; border-radius:50%; background:var(--forest); color:#fff; font-size:.75rem; font-weight:750; font-style:normal; }
    main { max-width:1540px; margin:0 auto; padding:54px 48px 42px; } h1,h2,h3,p { margin-top:0; } .intro { display:grid; grid-template-columns:minmax(0,1fr) 274px; gap:38px; align-items:start; margin-bottom:38px; } h1 { max-width:910px; margin-bottom:9px; color:var(--forest); font:400 clamp(2.9rem,5.1vw,4.65rem)/.98 Georgia,"Times New Roman",serif; letter-spacing:-.07em; } .lede { max-width:820px; margin:0; color:var(--muted); font-size:1.08rem; } .context { padding:20px 21px; border:1px solid var(--line); border-radius:8px; background:#fff; box-shadow:0 12px 24px rgba(20,53,42,.035); } .context h2 { margin-bottom:14px; font-size:.96rem; } .context p { display:flex; justify-content:space-between; gap:12px; margin:8px 0; color:var(--muted); font-size:.89rem; } .context strong { color:var(--forest); font-weight:750; }
    .work-layout { display:grid; grid-template-columns:minmax(265px,.82fr) minmax(430px,1.6fr) minmax(290px,.94fr); gap:18px; align-items:stretch; } .panel { min-width:0; border:1px solid var(--line); border-radius:8px; background:#fff; box-shadow:0 10px 30px rgba(20,53,42,.035); } .panel-header { display:flex; align-items:center; justify-content:space-between; gap:18px; min-height:59px; padding:0 20px; border-bottom:1px solid var(--line); } .panel-header h2 { margin:0; font:400 1.18rem Georgia,"Times New Roman",serif; letter-spacing:-.025em; } .quiet-link { color:var(--forest); font-size:.82rem; font-weight:700; text-decoration:none; } .quiet-link:hover { text-decoration:underline; }
    .queue { overflow:hidden; } .work-item { position:relative; display:flex; gap:13px; padding:21px 19px; border-bottom:1px solid var(--line); } .work-item.selected { background:#f1f8f4; } .work-item.selected::before { position:absolute; inset:0 auto 0 0; width:3px; background:var(--forest); content:""; } .work-icon { display:grid; flex:0 0 auto; place-items:center; width:38px; height:38px; margin-top:2px; border-radius:50%; background:var(--forest); color:#fff; font-size:1.07rem; } .work-copy { min-width:0; flex:1; } .work-copy strong,.work-copy span,.work-copy small { display:block; } .work-copy strong { margin-bottom:2px; font-size:.92rem; } .work-copy span { color:#44514f; font-size:.84rem; } .work-copy small { margin-top:3px; color:var(--muted); font-size:.76rem; } .status { align-self:center; padding:7px 9px; border:1px solid #a9cabc; border-radius:5px; color:var(--forest); font-size:.73rem; font-weight:750; white-space:nowrap; } .status.review { border-color:#e8b5b0; color:var(--danger); } .queue-footer { display:flex; align-items:center; justify-content:space-between; min-height:60px; padding:0 20px; }
    .reply { display:flex; flex-direction:column; } .message-meta { display:grid; grid-template-columns:114px minmax(0,1fr); gap:10px 16px; padding:21px 22px; border-bottom:1px solid var(--line); color:var(--muted); font-size:.86rem; } .message-meta strong { min-width:0; color:#33413e; font-weight:600; overflow-wrap:anywhere; } .message-body { flex:1; padding:25px 22px 23px; color:#293632; line-height:1.62; } .message-body p { margin-bottom:18px; } .reply-footer { display:flex; align-items:center; justify-content:space-between; gap:18px; min-height:73px; padding:12px 20px 12px 22px; border-top:1px solid var(--line); } .source-note { color:var(--muted); font-size:.77rem; } .send { display:inline-flex; align-items:center; justify-content:center; gap:9px; min-height:47px; padding:0 21px; border:1px solid var(--forest); border-radius:5px; background:var(--forest); color:#fff; cursor:pointer; font-weight:750; transition:transform .15s ease,background .15s ease; } .send:hover { background:var(--forest-deep); transform:translateY(-1px); } .send:focus-visible,.campaign-action:focus-visible { outline:3px solid var(--focus); outline-offset:3px; } .send:disabled,.campaign-action:disabled { cursor:wait; opacity:.7; transform:none; }
    .campaign { padding-bottom:4px; } .campaign-body { padding:23px 22px 11px; } .campaign-name { margin-bottom:24px; font-size:.95rem; font-weight:750; } .timeline { display:grid; gap:0; } .timeline-item { position:relative; display:grid; grid-template-columns:39px minmax(0,1fr); gap:14px; min-height:82px; } .timeline-item:not(:last-child)::after { position:absolute; top:37px; bottom:0; left:18px; width:1px; background:#cedbd5; content:""; } .timeline-icon { z-index:1; display:grid; place-items:center; width:37px; height:37px; border:1px solid #b2d0c2; border-radius:50%; background:#fff; color:var(--forest); font-size:1rem; } .timeline-icon.pending { background:#eff7f2; } .timeline-icon.stop { border-color:#d6ddda; color:#606d68; } .timeline-copy strong,.timeline-copy span { display:block; } .timeline-copy strong { margin-top:5px; font-size:.88rem; } .timeline-copy span { margin-top:2px; color:var(--muted); font-size:.77rem; } .campaign-action { width:calc(100% - 44px); min-height:42px; margin:3px 22px 18px; border:1px solid var(--forest); border-radius:5px; background:#fff; color:var(--forest); cursor:pointer; font-size:.83rem; font-weight:750; }
    .activity { margin-top:18px; padding:0 20px; } .activity-grid { display:grid; grid-template-columns:1fr 1fr 1fr minmax(210px,1.1fr); } .activity-item { display:flex; align-items:center; gap:13px; min-height:111px; padding:18px 17px 18px 0; border-right:1px solid var(--line); } .activity-item + .activity-item { padding-left:22px; } .activity-item:last-child { border:0; } .activity-icon { display:grid; flex:0 0 auto; place-items:center; width:39px; height:39px; border:1px solid #aed0c0; border-radius:50%; color:var(--forest); font-size:1rem; } .activity-icon.escalated { border-color:#e7b7b1; color:var(--danger); } .activity-copy strong,.activity-copy span { display:block; } .activity-copy strong { font-size:.84rem; } .activity-copy span { color:var(--muted); font-size:.76rem; } .activity-claim { color:#42514c; font-size:.86rem; }
    .live-note { display:flex; align-items:flex-start; gap:10px; margin-top:28px; padding:16px 18px; border-left:3px solid var(--forest); background:var(--wash); color:#495651; font-size:.84rem; } .live-note strong { color:var(--forest); } .result { position:fixed; right:24px; bottom:24px; z-index:4; display:none; width:min(400px,calc(100vw - 48px)); padding:20px; border:1px solid #b9d6c7; border-radius:8px; background:#f4faf7; box-shadow:0 20px 50px rgba(13,52,39,.17); } .result.visible { display:block; } .result[data-state="error"] { border-color:#e8b5b0; background:var(--danger-wash); } .result strong,.result span { display:block; } .result strong { margin-bottom:4px; color:var(--forest); font:400 1.24rem Georgia,"Times New Roman",serif; } .result span { color:#4d5b56; font-size:.86rem; } .result code { display:block; margin-top:11px; color:var(--muted); font: .72rem ui-monospace,SFMono-Regular,Menlo,monospace; overflow-wrap:anywhere; }
    @media (max-width:1120px) { .topbar { padding:0 28px; } main { padding:42px 28px; } .work-layout { grid-template-columns:minmax(255px,.8fr) minmax(420px,1.5fr); } .campaign { grid-column:1 / -1; } .campaign-body { display:grid; grid-template-columns:220px 1fr; gap:10px 30px; } .campaign-name { grid-row:1; margin:0; } .timeline { grid-column:2; grid-row:1; grid-template-columns:repeat(3,1fr); gap:12px; } .timeline-item { min-height:64px; } .timeline-item:not(:last-child)::after { top:18px; right:-14px; bottom:auto; left:auto; width:14px; height:1px; } .campaign-action { width:auto; margin:3px 22px 19px; } .activity-grid { grid-template-columns:1fr 1fr; } .activity-item:nth-child(2) { border-right:0; } }
    @media (max-width:740px) { .topbar { min-height:61px; padding:0 21px; } .brand { font-size:1.8rem; } .primary-nav { display:none; } .owner { margin-left:auto; } .owner span { display:none; } main { padding:34px 18px; } .intro { grid-template-columns:1fr; gap:21px; } h1 { font-size:3rem; } .work-layout { grid-template-columns:1fr; } .campaign { grid-column:auto; } .campaign-body { display:block; } .campaign-name { margin-bottom:20px; } .timeline { display:grid; grid-template-columns:1fr; } .timeline-item:not(:last-child)::after { top:37px; right:auto; bottom:0; left:18px; width:1px; height:auto; } .activity { padding:0 18px; } .activity-grid { grid-template-columns:1fr; } .activity-item,.activity-item + .activity-item { min-height:82px; padding:16px 0; border-right:0; border-bottom:1px solid var(--line); } .activity-item:last-child { border-bottom:0; } .message-meta { grid-template-columns:95px minmax(0,1fr); } .reply-footer { align-items:stretch; flex-direction:column; } .send { width:100%; } }
    @media (prefers-reduced-motion:reduce) { *,*::before,*::after { scroll-behavior:auto!important; transition:none!important; } }
  </style>
</head>
<body>
  <header class="topbar"><a class="brand" href="#work">Vice CEO</a><nav class="primary-nav" aria-label="Workspace"><a class="active" href="#work">Work</a><a href="#campaigns">Campaigns</a><a href="#activity">Activity</a></nav><div class="owner"><span>Westover EPR workspace</span><i class="avatar" aria-hidden="true">WE</i></div></header>
  <main id="work">
    <section class="intro"><div><h1>Work handled before it becomes work.</h1><p class="lede">Vice CEO drafts and sends routine replies, follows up with approved leads, and brings only exceptions to the owner.</p></div><aside class="context" aria-label="EPR context"><h2>EPR intelligence</h2><p><span>Account context</span><strong>Ready</strong></p><p><span>Message risk</span><strong>Low</strong></p><p><span>Registry change</span><strong>Reviewed</strong></p></aside></section>
    <section class="work-layout" aria-label="Business work queue">
      <article class="panel queue"><header class="panel-header"><h2>Work queue</h2><a class="quiet-link" href="/demo/judge-flow">How it works</a></header><div class="work-item selected"><span class="work-icon" aria-hidden="true">✉</span><div class="work-copy"><strong>Reset-password request</strong><span>Alex · Email</span><small>Just now · low-risk support</small></div><span class="status">Ready to send</span></div><div class="work-item"><span class="work-icon" aria-hidden="true">!</span><div class="work-copy"><strong>Refund request · #1042</strong><span>Mark · Web chat</span><small>45 min ago · needs judgment</small></div><span class="status review">Needs you</span></div><footer class="queue-footer"><strong>2 open items</strong><a class="quiet-link" href="#activity">See activity →</a></footer></article>
      <article class="panel reply"><header class="panel-header"><h2>Selected reply</h2><span class="status">Low-risk policy</span></header><div class="message-meta"><span>To</span><strong>Alex &lt;customer@example.invalid&gt;</strong><span>Subject</span><strong>Help with your password reset</strong><span>Source policy</span><strong>Support low-risk v1</strong></div><div class="message-body"><p>Hi Alex,</p><p>Thanks for reaching out. You can reset your password from the sign-in page using the “Forgot password” link. If the reset email does not arrive within a few minutes, reply here and we will help.</p><p>Best,<br>Westover EPR</p></div><footer class="reply-footer"><span class="source-note">Tied to inbound message · no account changes</span><button class="send" type="button" data-action="send_customer_reply">↗&nbsp; Send reply</button></footer></article>
      <article class="panel campaign" id="campaigns"><header class="panel-header"><h2>Outreach &amp; follow-ups</h2><a class="quiet-link" href="/demo/registry-watch">EPR context</a></header><div class="campaign-body"><p class="campaign-name">EPR readiness follow-up</p><div class="timeline"><div class="timeline-item"><span class="timeline-icon">✓</span><div class="timeline-copy"><strong>Email 1 sent</strong><span>Approved intro</span></div></div><div class="timeline-item"><span class="timeline-icon pending">◷</span><div class="timeline-copy"><strong>Follow-up queued</strong><span>Only for consented lead</span></div></div><div class="timeline-item"><span class="timeline-icon stop">■</span><div class="timeline-copy"><strong>Stops on reply</strong><span>Or unsubscribe</span></div></div></div></div><button class="campaign-action" type="button" data-action="send_outreach_follow_up">Run this follow-up</button></article>
    </section>
    <section class="panel activity" id="activity" aria-label="Recent activity"><header class="panel-header"><h2>Recent activity</h2><a class="quiet-link" href="/demo/proof-bundle">View action evidence</a></header><div class="activity-grid"><div class="activity-item"><span class="activity-icon">✓</span><div class="activity-copy"><strong>Account update</strong><span>Reply prepared · policy matched</span></div></div><div class="activity-item"><span class="activity-icon">◷</span><div class="activity-copy"><strong>Pricing follow-up</strong><span>Queued · consent checked</span></div></div><div class="activity-item"><span class="activity-icon escalated">!</span><div class="activity-copy"><strong>Refund #1042</strong><span>Escalated · owner review</span></div></div><div class="activity-item"><div class="activity-claim"><strong>Routine work moves forward.</strong><br>Only meaningful exceptions ask for attention.</div></div></div></section>
    <p class="live-note"><span aria-hidden="true">ⓘ</span><span><strong>Public demo boundary.</strong> The buttons create action receipts from fixed synthetic fixtures and do not send email. The private business-action service has a separate Resend delivery adapter, explicit enable switch, consent checks, source references, and idempotency protection before it can send from the Westover mailbox.</span></p>
  </main>
  <aside class="result" id="result" aria-live="polite" aria-atomic="true"><strong id="result-title">Working</strong><span id="result-message"></span><code id="result-details"></code></aside>
  <script>
    const result = document.getElementById('result'); const resultTitle = document.getElementById('result-title'); const resultMessage = document.getElementById('result-message'); const resultDetails = document.getElementById('result-details');
    function showResult(state, title, message, details = '') { result.className = 'result visible'; result.dataset.state = state; resultTitle.textContent = title; resultMessage.textContent = message; resultDetails.textContent = details; }
    document.querySelectorAll('[data-action]').forEach((button) => { button.addEventListener('click', async () => { document.querySelectorAll('[data-action]').forEach((control) => control.disabled = true); showResult('pending', 'Completing work item', 'Creating a traceable action receipt…'); try { const response = await fetch('/demo/business-actions', { method:'POST', headers:{'content-type':'application/json'}, body:JSON.stringify({action:button.dataset.action}) }); const payload = await response.json(); if (!response.ok || !payload.business_action) throw new Error(payload.detail || 'The work item could not be completed.'); const receipt = payload.business_action; const label = receipt.action_kind === 'customer_service_reply' ? 'Reply ready' : 'Follow-up ready'; showResult('success', label, 'A simulated action receipt was created. The public demo did not send an email.', receipt.receipt_id + ' · ' + receipt.idempotency_key); } catch (error) { showResult('error', 'No action was completed', error.message || 'Please try again.'); } finally { document.querySelectorAll('[data-action]').forEach((control) => control.disabled = false); } }); });
  </script>
</body>
</html>"""
